version: '3.9'

services:
  db:
    image: db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 60s
    networks:
      - net
    ports:
      - "5003:5003"
    volumes:
      - db:/db

  weather:
    image: weather
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    networks:
      - net
    ports:
      - "5001:5001"
    volumes:
      - db:/db

  worker:
    image: worker
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    depends_on:
      - weather
    networks:
      - net
    ports:
      - "5002:5002"
    volumes:
      - db:/db

  webserver:
    image: webserver
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    depends_on:
      - worker
    networks:
      - net
    ports:
      - "8080:8080"
    volumes:
      - db:/db

volumes:
  db:
  
networks:
  net:
    driver: overlay
