version: '3.9'

services:
  weather:
    container_name: weather
    image: weather
    build:
      context: .
      dockerfile: ./src/weather/Dockerfile
    depends_on:
      - builder
    ports:
      - "5001:5001"
    expose:
      - "5001"
    volumes:
      - db:/db

  webserver:
    container_name: webserver
    image: webserver
    build:
      context: .
      dockerfile: ./src/webserver/Dockerfile
    depends_on:
      - builder
      - worker
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - db:/db

  worker:
    container_name: worker
    image: worker
    build:
      context: .
      dockerfile: ./src/worker/Dockerfile
    depends_on:
      - builder
      - weather
    ports:
      - "5002:5002"
    expose:
      - "5002"
    volumes:
      - db:/db

  # builder image; just for convinience
  builder:
    image: builder
    build:
      context: .
      dockerfile: ./builder/Dockerfile

volumes:
  db:
